site_title = "MyArxiv"
limit_days = 7
cache_url = "https://julycrow.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "map learning"

[[sources]]
limit = 150
category = "cs.CV"
title = "hd map "


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
