site_title = "MyArxiv"
limit_days = 7
# cache_url = "https://julycrow.github.io/MyArxiv/cache.json"
cache_url = "https://github.com/julycrow/MyArxiv/blob/gh-pages/cache.json"

[[sources]]
limit = 1500
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

# [[sources]]
# limit = 150
# category = "cs.CV"
# title = "hd map "

# [[sources]]
# limit = 150
# category = "cs.CV"
# title = "map learning drive"

# [[sources]]
# limit = 150
# category = "cs.CV"
# title = "Lane Segment"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
